export const DISCORD_ID = "330950042863271936";
export const WORKER_URL =
  "https://portfolio-api.karlchastin-personal.workers.dev/";
export const defaultLayout = {
  showDiscord: false,
  showGithubStats: false,
  showLocMusic: false,
  showGithubContribs: false,
  showGithubRepos: false,
  showLocHome: false,
  showLocGithub: false,
  showLocSteam: false,
  showLocDiscord: false,
  showTimeLoc: false,
  showEmailActions: false,
  showSteamExtra: false,
  showSteamActivity: false,
  showSteamStats: false,
  showGithubAchievements: false,
  showSteamReview: false,
  showDiscordStatus: false,
  showSteamStatus: false,
  showDiscordBadges: false,
  showDiscordServers: false,
  showMusicActivity: false,
  showMusicPlaylists: false,
  showInstaHighlights: false,
  showInstaStats: false,
  showLocInsta: false,
  showInstaPosts: false,
  showFacebookStats: false,
  showLocFacebook: false,
  showSetup: false,
  showGameStats: false,
  showTiktok: false,
  showCards: [],
};
export const profiles = {
  home: {
    avatar: "./assets/Home%20Tab%20Avatar.webp",
    name: "chas",
    username: "",
    bio: "Tell me, do gods bleed?",
    layout: {
      ...defaultLayout,
      showDiscord: true,
      showMusic: true,
      showLocHome: true,
      showDiscordStatus: true,
      showCards: ["card-2-container", "card-3-container"],
    },
  },
  github: {
    avatar: "https://avatars.githubusercontent.com/u/244555740?v=4",
    name: "Karl Chastin Delfin",
    username: "@karlchastin",
    bio: "Loading live GitHub profile...",
    layout: {
      ...defaultLayout,
      showGithubStats: true,
      showGithubContribs: true,
      showGithubRepos: true,
      showLocGithub: true,
      showGithubAchievements: true,
      showCards: ["card-2-container", "card-3-container", "card-4-container"],
    },
  },
  email: {
    avatar:
      "https://lh3.googleusercontent.com/a/ACg8ocKT0TRPKQOi9HhhEUz48ZwapMWtuFTnsCNewew3vTrVOjs3F8jtsA=s1000-c",
    name: "Karl Chastin Delfin",
    username: "Choose your contact intention",
    bio: "Select a contact method below to reach out via your preferred email provider.",
    layout: {
      ...defaultLayout,
      showTimeLoc: true,
      showEmailActions: true,
      showCards: ["card-2-container"],
    },
  },
  steam: {
    avatar: "./assets/Home%20Tab%20Avatar.webp",
    name: "Loading...",
    username: "NotChztn",
    bio: "Welcome to my Steam profile. Let's play some games.",
    layout: {
      ...defaultLayout,
      showLocSteam: true,
      showSteamExtra: true,
      showSteamActivity: true,
      showSteamStats: true,
      showSteamReview: true,
      showSteamStatus: true,
      showCards: ["card-2-container", "card-3-container", "card-4-container"],
    },
  },
  discord: {
    avatar: "./assets/Home%20Tab%20Avatar.webp",
    name: "Discord",
    username: "@chas",
    bio: "<span class=\"bg-effect-exclude\" style=\"font-family: 'Consolas', monospace; background-color: rgba(0, 0, 0, 0.3); padding: 4px 6px; border-radius: 4px;\">I'll make a home in your gut, cause it's somewhere warm to sleep.</span>",
    layout: {
      ...defaultLayout,
      showLocDiscord: true,
      showDiscordStatus: true,
      showDiscordBadges: true,
      showDiscordServers: true,
      showCards: ["card-4-container"],
    },
  },
  apple_music: {
    avatar: "./assets/Apple%20Music%20Avatar.webp",
    name: "Karl Chastin Delfin",
    username: "@karlchastin",
    bio: "i am not responsible for these playlist names, they're just funny.",
    layout: {
      ...defaultLayout,
      showMusicActivity: true,
      showMusicPlaylists: true,
      showCards: ["card-2-container", "card-4-container"],
    },
  },
  instagram: {
    avatar: "./assets/Deactivated%20Profile%20Avatar.webp",
    name: "Loading...",
    username: "@karlchastin",
    bio: "Loading live Instagram profile...",
    layout: {
      ...defaultLayout,
      showLocInsta: true,
      showInstaStats: true,
      showInstaHighlights: true,
      showInstaPosts: true,
      showCards: ["card-2-container", "card-3-container", "card-4-container"],
    },
  },
  facebook: {
    avatar: "./assets/Deactivated%20Profile%20Avatar.webp",
    name: "Loading...",
    username: "@karlchastin",
    bio: "Loading live Facebook profile...",
    layout: {
      ...defaultLayout,
      showLocFacebook: true,
      showFacebookStats: true,
      showCards: ["card-3-container"],
    },
  },
  tiktok: {
    avatar: "./assets/Deactivated%20Profile%20Avatar.webp",
    name: "Loading...",
    username: "@karlchastin",
    bio: "Loading live TikTok profile...",
    layout: {
      ...defaultLayout,
      showTiktok: true,
      showCards: ["card-3-container"],
    },
  },
  setup: {
    avatar: "./assets/Gaming%20Rig%20Avatar.webp",
    name: "Setup",
    username: "",
    bio: "All hardware specifications and configurations.",
    layout: {
      ...defaultLayout,
      showSetup: true,
      showCards: ["card-2-container"],
    },
  },
  statistics: {
    avatar: "./assets/Game%20Statistics%20Avatar.webp",
    name: "Statistics",
    username: "",
    bio: "Performance trackers, preferred loadouts, and settings.",
    layout: {
      ...defaultLayout,
      showGameStats: true,
      showCards: ["card-2-container"],
    },
  },
};
export const SHES_MY_COLLAR_LYRICS = [
  { time: 29.3, text: "If I could take her down and run, then I'd call her" },
  { time: 32.88, text: "'Cause she's standing drama, she knows I'll call her" },
  { time: 36.5, text: "She's getting on the sun and then she order" },
  { time: 39.95, text: "Imagine me, imagine me now" },
  { time: 42.25, text: "(She's my collar)" },
  { time: 43.58, text: "I don't take her number, just don't think I'd call her" },
  { time: 47.17, text: "I take her down to somewhere drab and naughty" },
  { time: 50.65, text: "I clear my system, I don't need no other" },
  { time: 54.28, text: "This is my persona, secret lover" },
  { time: 55.92, text: "(She's my collar)" },
  { time: 58.16, text: "Nothing to be justified in" },
  { time: 61.59, text: "Just one thing, you should feel nada" },
  { time: 64.77, text: "I know she lies alone, she's my caller" },
  { time: 68.2, text: "I sense her in my mind, she's my collar" },
  { time: 84.66, text: "She's the serpentine, she's my collar" },
  { time: 88.31, text: "I send a message, never call her" },
  { time: 92.19, text: "And now I wanna taste another" },
  { time: 95.34, text: "And it's safe in a persona, she's my collar" },
  { time: 99.26, text: "Nothing to be justified in" },
  { time: 102.66, text: "She's the first I'm running with" },
  { time: 106.07, text: "She's the one that gets my collar" },
  { time: 109.5, text: "She's the one I'm running with" },
  { time: 110.78, text: "(She's my collar)" },
  { time: 112.88, text: "She's the one I'm running with" },
  { time: 116.25, text: "She's the one I'm running with" },
  { time: 119.73, text: "She's the one I'm running with" },
  { time: 124.37, text: "She's my collar" },
  { time: 126.39, text: "I'm yellow, he was blue" },
  { time: 129.8, text: "It's nothing that he could hide" },
  { time: 133.31, text: "We made a green meadow" },
  { time: 136.67, text: "Whenever we would collide" },
  { time: 140.24, text: "I died a thousand times" },
  { time: 143.54, text: "I did what I had to do" },
  { time: 146.82, text: "Hey, that's just how it goes" },
  { time: 150.36, text: "I'm still coming back to you" },
  { time: 152.62, text: "If I could take her down and run, then I'd call her" },
  { time: 156.17, text: "'Cause she's standing drama, she knows I'll call her" },
  { time: 159.83, text: "She's getting on the sun and then she order" },
  { time: 163.28, text: "Imagine me, imagine me now" },
  { time: 165.58, text: "(She's my collar)" },
  { time: 166.87, text: "I don't take her number, just don't think I'd call her" },
  { time: 170.6, text: "I take her down to somewhere drab and naughty" },
  { time: 173.99, text: "I clear my system, I don't need no other" },
  { time: 177.6, text: "This is my persona, secret lover (She's my collar)" },
  { time: 181.4, text: "She's the one I'm running with" },
  { time: 184.78, text: "She's the one I'm running with" },
  { time: 188.14, text: "She's the one I'm running with" },
  { time: 192.76, text: "She's my collar" },
  { time: 198.27, text: "Oh" },
  { time: 206.58, text: "She's my collar" },
];
export const featuredRepos = [
  {
    name: "Core Handler API",
    idName: "Core-Handler-API",
    desc: "An addon used as an API for other addons in Minecraft Bedrock edition.",
    private: true,
    banner: "linear-gradient(90deg, #2c3e50, #000)",
  },
  {
    name: "Chas' Java Combat Addon",
    idName: "chas-java-combat-addon",
    desc: "A project aimed to bring Minecraft Java Edition's combat mechanics to Minecraft Bedrock Edition!",
    private: false,
    url: "https://github.com/karlchastin/chas-java-combat-addon",
    banner: "linear-gradient(90deg, #ff0000, #330000)",
  },
  {
    name: "Project Salvation",
    idName: "Project-Salvation",
    desc: '"Project Salvation" is an independent Roblox passion project, heavily inspired by survival horror pioneers.',
    private: true,
    banner: "linear-gradient(90deg, #1a1a1a, #4d0000)",
  },
];
export const featuredServers = [
  {
    name: "World Peace Control Organization",
    desc: 'A group from the Roblox game "SCP: Roleplay". Chas\' main line of work by building in-game headquarters.',
    url: "https://discord.gg/hDXQuyfsgn",
    btnText: "JOIN DISCORD SERVER",
    banner: "linear-gradient(90deg, #1e3c72, #2a5298)",
  },
  {
    name: "Project Salvation's Community Server",
    desc: 'A Discord Server for the active development of the Roblox game "Project Salvation"',
    btnText: "PRIVATE SERVER",
    banner: "linear-gradient(90deg, #1a1a1a, #4d0000)",
  },
];
export const appleMusicPlaylists = [
  {
    name: "songs that makes me a white girl.",
    desc: "there literally isn't a better description here.",
    url: "https://music.apple.com/ph/playlist/songs-that-makes-me-a-white-girl/pl.u-qxylEMMsd7K3xbN",
    btnText: "LISTEN ON APPLE MUSIC",
    banner: "linear-gradient(90deg, #fa243c, #ff5e7e)",
  },
  {
    name: "songs i'd fuck you with.",
    desc: "that's a joke, by the way.",
    url: "https://music.apple.com/ph/playlist/songs-id-fuck-you-with/pl.u-zPyLl3vu85Xe2RG",
    btnText: "LISTEN ON APPLE MUSIC",
    banner: "linear-gradient(90deg, #8e2de2, #4a00e0)",
  },
];
export const instagramHighlights = [
  {
    title: "who",
    url: "https://www.instagram.com/stories/highlights/18111878254779115/",
    preview: "./assets/Instagram%20Highlight%20Thumbnail%20-%20who.webp",
  },
  {
    title: "what",
    url: "https://www.instagram.com/stories/highlights/18080284970579574/",
    preview: "./assets/Instagram%20Highlight%20Thumbnail%20-%20what.webp",
  },
  {
    title: "where",
    url: "https://www.instagram.com/stories/highlights/17886587631351183/",
    preview: "./assets/Instagram%20Highlight%20Thumbnail%20-%20where.webp",
  },
];
export const emailAvatars = {
  personal:
    "https://lh3.googleusercontent.com/a/ACg8ocKT0TRPKQOi9HhhEUz48ZwapMWtuFTnsCNewew3vTrVOjs3F8jtsA=s1000-c",
  business:
    "https://lh3.googleusercontent.com/a/ACg8ocJuf1q6J2ASav0wtbSxzLmSrDjZybT3LGBTEtDgQb23oN7r7aJv=s1000-c",
  school:
    "https://lh3.googleusercontent.com/a/ACg8ocISwd6aSM0UDXFLqiKEuYtdiKtJw1TNDDA-J2rTI62UO7OGsfvH=s1000-c",
};
export const emailBios = {
  personal:
    "Important and immediate concerns, networking, or NDA-protected inquiries.",
  business: "Professional opportunities, freelancing, and collaborations.",
  school: "Academic inquiries, professors, and university matters.",
};
export const discordBadges = [
  {
    name: "Nitro Platinum",
    desc: "Subscriber since 3/12/25",
    icon: "https://cdn.discordapp.com/badge-icons/0334688279c8359120922938dcb1d6f8.png",
  },
  {
    name: "Hypesquad Bravery",
    icon: "https://cdn.discordapp.com/badge-icons/8a88d63823d8a71cd5e390baa45efa02.png",
  },
  {
    name: "Server Boosting",
    desc: "Since Jul 1, 2026",
    icon: "https://cdn.discordapp.com/badge-icons/51040c70d4f20a921ad6674ff86fc95c.png",
  },
  {
    name: "Completed a Quest",
    icon: "https://cdn.discordapp.com/badge-icons/7d9ae358c8c5e118768335dbe68b4fb8.png",
  },
  {
    name: "Orbs",
    desc: "Apprentice",
    icon: "https://cdn.discordapp.com/badge-icons/83d8a1eb09a8d64e59233eec5d4d5c2d.png",
  },
  {
    name: "Gifting Hero",
    icon: "https://cdn.discordapp.com/badge-icons/77d65b1f210014a11eb1582ee06ab684.png",
  },
];
